server:
  port: 9050
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://git.oschina.net/itmuch/spring-cloud-config-repo.git
          # Git仓库账号
          username:
          # Git仓库密码
          password:

          #配置client
      uri: http://localhost:8080/
      profile: prod            # profile对应config server所获取的配置文件中的{profile}
      label: master           # 指定Git仓库的分支，对应config server所获取的配置文件的{label}