server:
  port: 8080
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://github.com/zylei21/springcloud-test.git
          # Git仓库账号
          username: zylei21
          # Git仓库密码
          password: Lei211314

          #配置client
      uri: http://localhost:8080/
      profile: dev            # profile对应config server所获取的配置文件中的{profile}
      label: master           # 指定Git仓库的分支，对应config server所获取的配置文件的{label}