spring:
  jpa:
    show-sql: true
  application:
    name: provider-user
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mqc520

server:
  port: 8001

logging:
  level:
    root : info
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
  endpoints:
    jmx:
      # 暴露metrics端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
      exposure:
        include: metrics

eureka:
  client:
    service-url:
      defaultZone: http://lsf:lsf123@peer2:8762/eureka/,http://lsf:lsf123@peer1:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
    lease-expiration-duration-in-seconds: 30 # 续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 10 # 续约更新时间间隔（默认30秒）ds